### ISSUE TITLE
We've to include routing.yml

### ISSUE THREAD

**Issue by alexandrezfs** [ultrasupernew/newsletterBundle#3]
Would be nice to tell users that we need to include the bundle routing actually 

```
#app/config/routing.yml

usn_newsletter:
    resource: "@UsnNewsletterBundle/Resources/config/routing.yml"
```

**Comment by Dragnucs** [comment]
Confirm.

**Comment by Dragnucs** [comment]
Hey @alexzhxin do you now of any serious and working with uptodate documentation Newsletter Bundle?

**Comment by maalls** [comment]
The documentation has been updated. 

@Dragnucs I am checking the bundle right now and I am going to clean it up based on your feedbacks. Thanks!
